name: material_design_system
description: "A Flutter package for a consistent and easy-to-use design system based on Material Design 3 tokens."
version: 0.0.1
# author: Kevin Kobori <https://www.linkedin.com/in/kevin-kobori/>
homepage:
repository: https://github.com/fluttely/material_design_system
issue_tracker: https://github.com/fluttely/material_design_system/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_design: ^0.2.6
  material_toolkit: ^0.2.0
  # material_design:
  #   path: packages/material_toolkit/packages/material_design
  # material_toolkit:
  #   path: packages/material_toolkit

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
