name: material_design_system
description: "A new Flutter package project."
version: 0.0.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_design: ^0.2.6
  material_tookit: ^0.2.0
  # material_design:
  #   path: packages/material_toolkit/packages/material_design
  # material_toolkit:
  #   path: packages/material_toolkit

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
